openapi: 3.0.0
servers:
  - description: Local Dev Server
    url: 'http://localhost:8080'
info:
  description: User Service API
  version: "0.0.2"
  title: User Service API
tags:
  - name: user
    description: users actions related api

paths:
  /:
    get:
      tags:
        - user
      summary: search users
      operationId: searchUsers
      description: List users
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDto'
        '400':
          description: bad input parameters
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '404':
          description: not found
        '409':
          description: conflict
        '500':
          description: internal error

components:
  schemas:
    UserDto:
      type: object
      required: [ name, email ]
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          description: User id
        createdAt:
          type: string
          format: date-time
          readOnly: true
          description: Creation date
        name:
          type: string
          maxLength: 255
          description: User name
        surname:
          type: string
          maxLength: 255
          description: User surname
        email:
          type: string
          description: User email
