openapi: 3.0.0
servers:
  - description: Local Dev Server
    url: 'http://localhost:8080'
info:
  description: User Service API
  version: "0.0.1"
  title: User Service API
tags:
  - name: user
    description: users actions related api

paths:
  /:
    get:
      tags:
        - user
      summary: search users
      operationId: searchUsers
      description: List users
      responses:
        '200':
          description: search results matching criteria
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/ProductPage'
        '400':
          description: bad input parameter
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: internal error
