intelligence:
  db:
    schema-name: intelligence_user_service
    url: jdbc:postgresql://localhost:5432/Intelligence
    username: postgres
    password: postgres

com.intelligence.user:
  host: localhost
server:
  port: 8080

logger:
  level:
    org.hibernate.SQL: DEBUG
